import type { CalendarEvent } from './icsUtils';
import { GENERATED_GREEK_EVENTS } from './generated/greekTheaterEvents';

export interface GreekTheaterEvent {
  date: Date;
  title: string;
  url: string;
  showTime?: string;
  doorsTime?: string;
  /** Parking impact severity (Greek concerts are always 'medium') */
  severity: 'high' | 'medium' | 'low';
  note?: string;
}

// Convert Greek Theater event to CalendarEvent format for the modal
export function greekTheaterToCalendarEvent(greekEvent: GreekTheaterEvent): CalendarEvent {
  // Use local date components to create ISO string, avoiding UTC shift
  // Greek Theater dates are constructed with new Date(year, month, day) (local timezone)
  const d = greekEvent.date;
  const localIso = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}T12:00:00`;
  return {
    uid: `greek-${greekEvent.date.getTime()}`,
    title: ` ${greekEvent.title}`,
    start: localIso,
    end: localIso,
    description: `Greek Theater Berkeley presents: ${greekEvent.title}${greekEvent.showTime ? `\n\nShow Time: ${greekEvent.showTime}` : ''}${greekEvent.doorsTime ? `\nDoors: ${greekEvent.doorsTime}` : ''}\n\nGet tickets: ${greekEvent.url}`,
    url: greekEvent.url,
    location: 'Greek Theater, Berkeley, CA'
  };
}

export function parseGreekTheaterEvents(): GreekTheaterEvent[] {
  // Data is generated by scripts/event-parking/update_parking_events.py
  // (weekly Mar-Oct, monthly Nov-Feb) into lib/generated/greekTheaterEvents.ts.
  // Concerts only — the Greek does not list UC non-concert events (known gap).
  return GENERATED_GREEK_EVENTS.map((e) => ({
    date: new Date(e.year, e.month - 1, e.day), // month is 0-indexed in Date
    title: e.title,
    url: e.url,
    showTime: e.showTime,
    doorsTime: e.doorsTime,
    severity: e.severity,
    note: e.note,
  }));
}

export function getGreekTheaterEventsForDate(date: Date): GreekTheaterEvent[] {
  const events = parseGreekTheaterEvents();
  return events.filter(event => 
    event.date.getFullYear() === date.getFullYear() &&
    event.date.getMonth() === date.getMonth() &&
    event.date.getDate() === date.getDate()
  );
}

export function hasGreekTheaterEventOnDate(date: Date): boolean {
  return getGreekTheaterEventsForDate(date).length > 0;
}
